version: '3'
services:
  back:
    container_name: instructBack
    build: back/
    ports:
      - "8090:8090"
    volumes:
      - ./db/pb_migrations/:/pb_migrations
      - ./db/pb_data/:/pb_data/
  frontend:
    container_name: instructWeb
    build: front
    env_file:
      - .env
    ports:
      - "3000:5173"
    
volumes:
  node_modules:
  
